name : financial-superapp
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - pandas_datareader
  - matplotlib
  - yfinance
  - streamlit
  - scipy
  - plotly
  - pip
  - pip :
    - fmpsdk
